<!DOCTYPE html>
<html lang="en">
<head>
    <?php include(SHARED_PATH . '/headMain.inc'); ?>    
</head>

<body>

    <?php include(SHARED_PATH . '/headerMain.inc'); ?>

    <main>
        <h1 id="homeHeader"><?php echo $pageTitle ?></h1>

        <article id="content">

            <h3>Under Development.....</h3>

        </article>
    </main>

    <?php include(SHARED_PATH . '/footer.inc'); ?>
    
</body>
</html>